# Generated by Django 5.1.7 on 2025-03-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
