# Generated by Django 5.1.7 on 2025-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_remove_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.IntegerField(default=20),
        ),
    ]
